#!/bin/bash
## ---------------------------------------------------------------------
## Copyright (C) 2019 - 2022 by the lifex authors.
##
## This file is part of lifex.
##
## lifex is free software; you can redistribute it and/or modify
## it under the terms of the GNU Lesser General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## lifex is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
## Lesser General Public License for more details.
##
## You should have received a copy of the GNU Lesser General Public License
## along with lifex.  If not, see <http://www.gnu.org/licenses/>.
## ---------------------------------------------------------------------

# Author: Pasquale Claudio Africa <pasqualeclaudio.africa@polimi.it>.

##
## This script has been readapted from the corresponding file
## available at the deal.II development repository
## (https://github.com/dealii/dealii),
## released under compatible license terms
## (please consult the doc/licenses directory for more information).
##

#
# This pre-commit hook checks formatting for each commit.
#

BASEDIR="$(git rev-parse --show-toplevel 2>/dev/null)"

if [ ! -f "${BASEDIR}"/scripts/format/indent ]; then
  echo "*** This script must be run from within the lifex git repository."
  exit 1
fi

cd "${BASEDIR}"
OUTPUT="$(REPORT_ONLY=true "${BASEDIR}"/scripts/format/indent)"

if [ ! -z "${OUTPUT}" ]; then
  echo "git commit aborted due to formatting issues:"
  echo "${OUTPUT}"
  echo ""
  echo "Please run ./scripts/format/indent to fix these issues and try again."
  exit 1
fi
